FUNCTION(PATH_TO_NAME path)
    STRING(REPLACE "${CMAKE_SOURCE_DIR}/" "" path "${path}")
    IF(UNIX)
        STRING(REPLACE "/" "-" result "${path}")
    ELSE()
        STRING(REPLACE "\\" "-" result "${path}")
    ENDIF()
    SET(_RESULT "${result}" PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(TARGET_NAME)
    PATH_TO_NAME("${CMAKE_CURRENT_LIST_DIR}")
    SET(TARGET_NAME "${_RESULT}" PARENT_SCOPE)
ENDFUNCTION()
